# Generated by Django 4.2 on 2024-12-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0004_progress_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_app.chapter'),
        ),
    ]
