# Generated by Django 5.1.4 on 2024-12-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0005_alter_progress_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='article',
        ),
    ]
